// 3.vue/5.server-render/nuxt-realworld/components/Login.vue
<template>
    <div class="auth-page">
        <div class="container page">
            <div class="row">
                <div class="col-md-6 offset-md-3 col-xs-12">
                    <h1 class="text-xs-center">
                        {{ isLogin ? "Sign in" : "Sign up" }}
                    </h1>
                    <p class="text-xs-center">
                        <NuxtLink v-if="isLogin" href="/register"
                            >Need an account?</NuxtLink
                        >
                        <NuxtLink v-else href="/login"
                            >Have an account?</NuxtLink
                        >
                    </p>

                    <ul class="error-messages">
                        <template
                            v-for="(messages, field) in errors"
                            :key="field"
                        >
                            <li
                                v-for="(message, index) in messages"
                                :key="index"
                            >
                                {{ field }} {{ message }}
                            </li>
                        </template>
                    </ul>

                    <form @submit.prevent="handleSubmit">
                        <fieldset v-if="!isLogin" class="form-group">
                            <input
                                v-model="username"
                                class="form-control form-control-lg"
                                type="text"
                                placeholder="Username"
                            />
                        </fieldset>
                        <fieldset class="form-group">
                            <input
                                v-model="user.email"
                                class="form-control form-control-lg"
                                type="email"
                                placeholder="Email"
                                required
                            />
                        </fieldset>
                        <fieldset class="form-group">
                            <input
                                v-model="user.password"
                                class="form-control form-control-lg"
                                type="password"
                                required
                                placeholder="Password"
                            />
                        </fieldset>
                        <button class="btn btn-lg btn-primary pull-xs-right">
                            {{ isLogin ? "Sign in" : "Sign up" }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">

const props = defineProps({
    isLogin: {
        type: Boolean,
        default: false,
    },
    errors: {
        type: Object,
        default: () => ({}),
    },
})
const emit = defineEmits(["submit"])

const username = ref("")
const user = reactive({
    email: "",
    password: "",
})

const handleSubmit = () => {
    if (!props.isLogin) {
        // 注册
        emit("submit", { ...toRaw(user), username: username.value })
    } else {
        // 登录
        emit("submit", toRaw(user))
    }
}
</script>

<style scoped></style>

// 5.react/6.ssr/gatsby-ssr/src/components/login.tsx
import React from "react"
import useInput from "../hooks/useInput"
import { navigate } from "gatsby"
import { useAuthStore } from "../store"

export default function Login() {
  const auth = useAuthStore()
  const email = useInput("")
  const password = useInput("")

  if (auth.success) {
    navigate("/")
    return null
  }
  function displayErrors() {
    if (auth.errors) {
      return auth.errors.map((item: any, index: any) => (
        <li key={index}>{item}</li>
      ))
    }
    return null
  }
  function handleSubmit(e: any) {
    e.preventDefault()
    const passwordValue = password.input.value
    const emailValue = email.input.value
    auth.login({ user: { email: emailValue, password: passwordValue } })
  }
  return (
    <div className="auth-page">
      <div className="container page">
        <div className="row">
          <div className="col-md-6 offset-md-3 col-xs-12">
            <h1 className="text-xs-center">Sign up</h1>
            <ul className="error-messages">{displayErrors()}</ul>
            <form onSubmit={handleSubmit}>
              <fieldset className="form-group">
                <input
                  className="form-control form-control-lg"
                  type="text"
                  placeholder="Email"
                  {...email.input}
                />
              </fieldset>
              <fieldset className="form-group">
                <input
                  className="form-control form-control-lg"
                  type="password"
                  placeholder="Password"
                  {...password.input}
                />
              </fieldset>
              <button className="btn btn-lg btn-primary pull-xs-right">
                Sign In
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}
